### ISSUE TITLE
Add usage cost

### ISSUE THREAD

**Issue by xescugc** [cycloidio/terracost#96]
Some resources do not have specific attributes that would be used to calculate the price, this price is set when the resource is used. For this we'll allow a specific file that would specify that usage for the specific resources so we can make a estimation on their usage instead of having a 0 cost.

The format of this file for now will be:

```yaml
resource_type_default_usage:
    aws_lambda_function:
      monthly_requests: 100000 # Monthly requests to the Lambda function.
      request_duration_ms: 500 # Average duration of each request in milliseconds.
```
